version: '3.3'

services:
  fluentbit:
    image: fluentbitdev/fluent-bit:x86_64-master
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -i node_exporter_metrics -p path.procfs=/host/proc -p path.sysfs=/host/sys -o prometheus_exporter -p "add_label=name fluentbit" -f 1
    ports:
      - 2021:2021
    networks:
      - exporter-network
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys

networks:
  exporter-network:
    driver: bridge